version: "3.9"
services:
    web:
        image: "ostashev/xaf-container-example:latest"
        ports:
          - "80:80"
        environment:
          - CONNECTION_STRING=DockerComposeMSSQLConnectionString
        networks:
          - my-network
            
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Qwerty1_"
            ACCEPT_EULA: "Y"
        networks:
          - my-network
networks:
  my-network:
    internal: true